# Generated by Django 2.0 on 2018-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20180810_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='contact_man',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='紧急联系人'),
        ),
        migrations.AddField(
            model_name='staff',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='紧急联系人号码'),
        ),
        migrations.AddField(
            model_name='staff',
            name='contact_relation',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='紧急联系人关系'),
        ),
        migrations.AddField(
            model_name='staff',
            name='recruit_channel',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='招聘渠道'),
        ),
        migrations.AddField(
            model_name='staff',
            name='referrer',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='引荐人'),
        ),
        migrations.AddField(
            model_name='staff',
            name='remark',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
    ]
