# Generated by Django 2.0 on 2018-08-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_auto_20180811_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='department',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='personnel.Department', verbose_name='所属部门'),
        ),
    ]
