# Generated by Django 2.0 on 2018-08-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_auto_20180811_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='job_title',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.JobTitle', verbose_name='职称'),
        ),
    ]
