# Generated by Django 2.0 on 2018-08-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_auto_20180813_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='life_photo',
        ),
        migrations.AlterField(
            model_name='stafflifephoto',
            name='life_photo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='路径'),
        ),
    ]
