# Generated by Django 2.0 on 2018-08-10 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=32, null=True, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=32, verbose_name='工号')),
                ('name', models.CharField(max_length=32, verbose_name='员工姓名')),
                ('life_photo', models.CharField(blank=True, max_length=128, null=True, verbose_name='生活照片')),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('company', models.CharField(blank=True, max_length=128, null=True, verbose_name='公司名称')),
                ('project', models.CharField(blank=True, max_length=64, null=True, verbose_name='所在项目')),
                ('job_rank', models.CharField(blank=True, max_length=64, null=True, verbose_name='职级')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('is_lunar', models.SmallIntegerField(choices=[(0, '公历'), (1, '农历')], default=0, verbose_name='生日农历or公历')),
                ('hire_day', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('native_place', models.CharField(blank=True, max_length=64, null=True, verbose_name='籍贯')),
                ('nationality', models.CharField(blank=True, max_length=32, null=True, verbose_name='民族')),
                ('family_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭住址')),
                ('current_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='现住地址')),
                ('education', models.CharField(blank=True, max_length=32, null=True, verbose_name='学历')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('bank', models.CharField(blank=True, max_length=32, null=True, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=21, null=True, verbose_name='银行账号')),
                ('delete_status', models.SmallIntegerField(choices=[(0, '已删除'), (1, '保留')], default=1, verbose_name='删除状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('department', models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='personnel.Department', verbose_name='所属部门')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='具有的所有的角色')),
                ('user', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='StaffAttach',
            fields=[
                ('said', models.AutoField(primary_key=True, serialize=False)),
                ('attach', models.CharField(blank=True, max_length=512, null=True, verbose_name='附件路径')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='附件名称')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='附件描述')),
                ('sid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='personnel.Staff', verbose_name='员工')),
            ],
            options={
                'verbose_name': '员工附件',
                'verbose_name_plural': '员工附件',
                'db_table': 'staff_attach',
            },
        ),
    ]
