# Generated by Django 2.0 on 2018-08-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Rank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, max_length=32, null=True, verbose_name='职级')),
            ],
            options={
                'verbose_name': '职级',
                'verbose_name_plural': '职级',
                'db_table': 'job_rank',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(blank=True, max_length=32, null=True, verbose_name='所在项目')),
            ],
            options={
                'verbose_name': '所在项目',
                'verbose_name_plural': '所在项目',
                'db_table': 'project',
            },
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_rank',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='personnel.Job_Rank', verbose_name='职级'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='project',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='personnel.Project', verbose_name='所在项目'),
        ),
    ]
