# Generated by Django 2.0 on 2018-08-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20180810_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_Rank',
            new_name='JobRank',
        ),
    ]
