# Generated by Django 2.0 on 2018-08-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_auto_20180810_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='account_name',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='开户人'),
        ),
    ]
