# Generated by Django 2.0 on 2018-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_staff_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=32, null=True, verbose_name='公司')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='职称')),
            ],
            options={
                'verbose_name': '职称',
                'verbose_name_plural': '职称',
                'db_table': 'job_title',
            },
        ),
        migrations.RenameField(
            model_name='staffattach',
            old_name='attach',
            new_name='attachment',
        ),
    ]
