# Generated by Django 2.0 on 2018-08-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_auto_20180811_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='job_title',
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_rank',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.JobRank', verbose_name='职级'),
        ),
    ]
