# Generated by Django 2.0 on 2018-07-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=32, null=True, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Performemce',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='绩效名称')),
                ('personal_score', models.IntegerField(verbose_name='个人分值')),
                ('personal_total', models.IntegerField(verbose_name='个人总分')),
                ('team_score', models.IntegerField(verbose_name='团队分值')),
                ('team_total', models.IntegerField(verbose_name='团队总分')),
            ],
            options={
                'verbose_name': '绩效分类',
                'verbose_name_plural': '绩效分类',
                'db_table': 'performemce',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='员工姓名')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512, verbose_name='任务名称')),
                ('content', models.TextField(verbose_name='任务描述')),
                ('issuer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='task.Staff', verbose_name='发布人')),
                ('status', models.IntegerField(choices=[(1, '启动'), (2, '暂停'), (3, '终止')], default=1, verbose_name='任务状态')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_edit', models.DateTimeField(verbose_name='最后编辑时间')),
            ],
            options={
                'verbose_name': '任务内容',
                'verbose_name_plural': '任务内容',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskAssign',
            fields=[
                ('tasid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='任务名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='任务内容')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('progress', models.SmallIntegerField(default=0, verbose_name='完成进度(%)')),
                ('is_finish', models.SmallIntegerField(choices=[(0, '未通过'), (1, '通过')], default=0, verbose_name='审核状态')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_edit', models.DateTimeField(verbose_name='最后编辑时间')),
            ],
            options={
                'verbose_name': '任务指派内容',
                'verbose_name_plural': '任务指派内容',
                'db_table': 'task_assign',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignAttach',
            fields=[
                ('taaid', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.CharField(blank=True, max_length=512, null=True, verbose_name='附件路径')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='附件名称')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='附件描述')),
                ('tasid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.TaskAssign', verbose_name='指派任务')),
            ],
            options={
                'verbose_name': '任务指派附件',
                'verbose_name_plural': '任务指派附件',
                'db_table': 'task_assign_attach',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignTag',
            fields=[
                ('tatid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='标签名称')),
                ('tasid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.TaskAssign', verbose_name='指派任务')),
            ],
            options={
                'verbose_name': '任务指派标签',
                'verbose_name_plural': '任务指派标签',
                'db_table': 'task_assign_tag',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('tamid', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.CharField(blank=True, max_length=512, null=True, verbose_name='附件路径')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='附件名称')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='附件描述')),
                ('tid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务附件',
                'verbose_name_plural': '任务附件',
                'db_table': 'task_attachment',
            },
        ),
        migrations.CreateModel(
            name='TaskAuth',
            fields=[
                ('taid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('result', models.IntegerField()),
                ('score', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('last_edit', models.DateTimeField()),
                ('tasid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.TaskAssign', verbose_name='指派任务')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'task_auth',
            },
        ),
        migrations.CreateModel(
            name='TaskCycle',
            fields=[
                ('tcid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='任务周期')),
            ],
            options={
                'verbose_name': '任务周期',
                'verbose_name_plural': '任务周期',
                'db_table': 'task_cycle',
            },
        ),
        migrations.CreateModel(
            name='TaskMap',
            fields=[
                ('tmid', models.AutoField(primary_key=True, serialize=False)),
                ('assigner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='task.Staff', verbose_name='指派人')),
                ('execute_way', models.IntegerField(choices=[(0, '并行执行'), (1, '次序执行')], verbose_name='执行方式')),
                ('teamwork_auth', models.IntegerField(choices=[(0, '相互可见'), (1, '互不可见'), (3, '指定可见')], default=1, verbose_name='是否可见')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='起始时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('is_finish', models.IntegerField(choices=[(0, '进行中'), (1, '已完成')], default=0, verbose_name='完成状态')),
                ('team', models.IntegerField(choices=[(0, '个人任务'), (1, '组队任务')], default=0, verbose_name='任务方式')),
                ('status', models.IntegerField(choices=[(1, '启动'), (2, '暂停'), (3, '终止')], default=1, verbose_name='任务状态')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_edit', models.DateTimeField(verbose_name='最后编辑时间')),
                ('cycle', models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='task.TaskCycle', verbose_name='任务周期')),
                ('perfor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.Performemce', verbose_name='绩效分类')),
                ('tid', models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='任务ID')),
            ],
            options={
                'verbose_name': '任务指派',
                'verbose_name_plural': '任务指派',
                'db_table': 'task_map',
            },
        ),
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('tvid', models.AutoField(primary_key=True, serialize=False)),
                ('follow', models.IntegerField(verbose_name='审核顺序')),
                ('sid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.Staff', verbose_name='审核人')),
                ('tmid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.TaskMap', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务审核人',
                'verbose_name_plural': '任务审核人',
                'db_table': 'task_review',
            },
        ),
        migrations.CreateModel(
            name='TaskReviewRecord',
            fields=[
                ('trrid', models.AutoField(primary_key=True, serialize=False)),
                ('is_complete', models.SmallIntegerField(choices=[(0, '未完成'), (1, '已完成')], verbose_name='审核状态')),
                ('evaluate', models.FloatField(blank=True, null=True, verbose_name='星级评分')),
                ('create_time', models.DateTimeField(verbose_name='审核时间')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='原因')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评语')),
                ('tasid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.TaskAssign', verbose_name='指派任务')),
                ('tvid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.TaskReview', verbose_name='任务审核分配id')),
            ],
            options={
                'verbose_name': '任务审核记录',
                'verbose_name_plural': '任务审核记录',
                'db_table': 'task_review_record',
            },
        ),
        migrations.CreateModel(
            name='TaskSubmitAttachment',
            fields=[
                ('tsaid', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.CharField(blank=True, max_length=512, null=True, verbose_name='附件路径')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='附件名称')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='附件描述')),
            ],
            options={
                'verbose_name': '工作提交附件',
                'verbose_name_plural': '工作提交附件',
                'db_table': 'task_submit_attachment',
            },
        ),
        migrations.CreateModel(
            name='TaskSubmitRecord',
            fields=[
                ('tsid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='标题')),
                ('summary', models.CharField(blank=True, max_length=512, null=True, verbose_name='小结')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
                ('completion', models.SmallIntegerField(default=0, verbose_name='完成度(%)')),
                ('is_assist', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否寻求协助')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_edit', models.DateTimeField(verbose_name='最后编辑时间')),
                ('tasid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.TaskAssign', verbose_name='指派任务')),
            ],
            options={
                'verbose_name': '工作提交记录',
                'verbose_name_plural': '工作提交记录',
                'db_table': 'task_submit_record',
            },
        ),
        migrations.CreateModel(
            name='TaskSubmitTag',
            fields=[
                ('tstid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='标签')),
                ('tsid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.TaskSubmitRecord', verbose_name='任务提交')),
            ],
            options={
                'verbose_name': '工作提交标签',
                'verbose_name_plural': '工作提交标签',
                'db_table': 'task_submit_tag',
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('ttid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='标签名称')),
                ('tid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务标签',
                'verbose_name_plural': '任务标签',
                'db_table': 'task_tag',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('tpid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '任务类型',
                'verbose_name_plural': '任务类型',
                'db_table': 'task_type',
            },
        ),
        migrations.AddField(
            model_name='tasksubmitattachment',
            name='tsid',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.TaskSubmitRecord', verbose_name='工作提交'),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='member_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.Staff', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='tmid',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.TaskMap', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='task',
            name='cycle',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='task.TaskCycle', verbose_name='任务周期'),
        ),
        migrations.AddField(
            model_name='task',
            name='perfor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.Performemce', verbose_name='绩效分类'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='task.TaskType', verbose_name='任务类型'),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Department', verbose_name='所属部门'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktag',
            unique_together={('tid', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tasksubmittag',
            unique_together={('tsid', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskreview',
            unique_together={('tmid', 'sid')},
        ),
        migrations.AlterUniqueTogether(
            name='taskassigntag',
            unique_together={('tasid', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskassign',
            unique_together={('tmid', 'member_id')},
        ),
    ]
