# Generated by Django 2.0 on 2018-07-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmap',
            name='remark',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, '启动'), (2, '暂停'), (3, '取消')], default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='taskmap',
            name='status',
            field=models.IntegerField(choices=[(1, '启动'), (2, '暂停'), (3, '取消')], default=1, verbose_name='任务状态'),
        ),
    ]
