# Generated by Django 2.0 on 2018-07-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180718_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='perfor',
        ),
    ]
