# Generated by Django 2.0 on 2018-07-23 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_remove_task_perfor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': (('publish_task', '发布任务'), ('task_edit', '任务编辑'), ('task_detail', '任务详情')), 'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
        migrations.AlterModelOptions(
            name='taskmap',
            options={'verbose_name': '任务指派记录', 'verbose_name_plural': '任务指派记录'},
        ),
        migrations.AddField(
            model_name='staff',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='staff',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='staff',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='current_project',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='职级'),
        ),
        migrations.AddField(
            model_name='staff',
            name='delete_status',
            field=models.SmallIntegerField(choices=[(0, '已删除'), (1, '保留')], default=1, verbose_name='删除状态'),
        ),
        migrations.AddField(
            model_name='staff',
            name='education',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='staff',
            name='hire_day',
            field=models.DateField(blank=True, null=True, verbose_name='入职日期'),
        ),
        migrations.AddField(
            model_name='staff',
            name='job_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='staff',
            name='native_place',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='籍贯'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='staff',
            name='project',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='所在项目'),
        ),
        migrations.AddField(
            model_name='staff',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='delete_status',
            field=models.SmallIntegerField(choices=[(0, '已删除'), (1, '保留')], default=1, verbose_name='删除状态'),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='delete_status',
            field=models.SmallIntegerField(choices=[(0, '已删除'), (1, '保留')], default=1, verbose_name='删除状态'),
        ),
        migrations.AddField(
            model_name='taskreviewrecord',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=32, verbose_name='员工姓名'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, '启动'), (0, '删除')], default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
        migrations.AlterField(
            model_name='taskauth',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskauth',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
        migrations.AlterField(
            model_name='taskmap',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskmap',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
        migrations.AlterField(
            model_name='taskmap',
            name='status',
            field=models.IntegerField(choices=[(1, '进行中'), (2, '暂停'), (3, '取消')], default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='taskmap',
            name='tid',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='taskreviewrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='tasksubmitrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tasksubmitrecord',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
    ]
